version: "3.8"

services:

  redis:
    image: redis:5
    init: true

  worker:
    init: true
    image: worker-image
    volumes:
      - ./backend:/home/python/code
    build:
      context: ./backend/worker
      dockerfile: Dockerfile
    env_file:
      - ./env/.rq.env
    command: /bin/bash -c "wait-for-it -s -t 60 redis:6379 && rq worker --url redis://redis:6379"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  django:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - redis
      - worker
      - postgres
    environment:
      - NC2ZARR_PROD=True

  postgres:
    image: postgres
    restart: always

  angular-frontend:
    build: ./frontend

  nginx:
    image: nginx