version: "3.8"

services:

  rq-dashboard:
    image: ucyo/rq-dashboard:latest
    init: true
    env_file:
      - ./env/.rq.env
    depends_on:
      - redis
      - worker
    ports:
      - "9181:9181"

  rebrow:
    image: marian/rebrow
    init: true
    ports:
      - "5001:5001"

  jupyter:
    build: ./jupyter
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"

  redis:
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  worker:
    volumes:
      - ./intake-catalogs:/home/python/intake-catalogs
      - ./input:/home/python/input
      - ./output:/home/python/output
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.25'
          memory: 3G

  django:
    volumes:
      - ./input:/input
      - ./output:/output
      - ./intake-catalogs:/intake-catalogs
    ports:
      - "8000:8000"
    environment:
      - NC2ZARR_PROD=True
      - NC2ZARR_INPUT=/input
      - NC2ZARR_OUTPUT=/output
      - NC2ZARR_INTAKE_CATALOGS=/intake-catalogs
      - NC2ZARR_POSTGRES_PASSWORD=development
      - NC2ZARR_URL=localhost

  angular-frontend:
    ports:
      - "80:80"
    environment:
      - NC2ZARR_WEB_INTERFACE_URL=http://localhost
      - NC2ZARR_CONTENT_URL=http://localhost:8080

  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=development

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80