version: "3.8"

services:

  rq-dashboard:
    ports:
      - "9181:9181"

  redis:
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  worker:
    volumes:
      - ./backend:/home/python/code
      - ./input:/home/python/input
      - ./output:/home/python/output
      - ./intake-catalogs:/home/python/intake-catalogs
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.25'
          memory: 3G

  django:
    volumes:
      - ./input:/input
      - ./output:/output
      - ./intake-catalogs:/intake-catalogs